plugins:
  post_badges_plugin_enabled:
    default: true
    client: true
  post_badges_badges:
    type: list
    default: ""
    client: true
  post_badges_badge_link_destination:
    type: enum
    default: "user's badge page"
    client: true
    choices:
      - "user's badge page"
      - "badge overview page"
  post_badges_only_show_highest_trust_level:
    type: bool
    default: false
    client: true
